ALTER TABLE `wD_Games` ADD `phase2Minutes` SMALLINT( 5 ) UNSIGNED NOT NULL DEFAULT '1440';
ALTER TABLE `wD_Games` ADD `phase3Minutes` SMALLINT( 5 ) UNSIGNED NOT NULL DEFAULT '1440';
ALTER TABLE `wD_Backup_Games` ADD `phase2Minutes` SMALLINT( 5 ) UNSIGNED NOT NULL DEFAULT '1440';
ALTER TABLE `wD_Backup_Games` ADD `phase3Minutes` SMALLINT( 5 ) UNSIGNED NOT NULL DEFAULT '1440';
